name: Pull request linting

on:
  push:
    paths:
      - "src/communication/*.py"
      - "src/controller/*.py"
      - "src/fusion/*.py"
      - "src/motors/*.py"
      - "src/*.py"
  pull_request:
    paths:
      - "src/communication/*.py"
      - "src/controller/*.py"
      - "src/fusion/*.py"
      - "src/motors/*.py"
      - "src/*.py"

jobs:
  lint:
    runs-on: ubuntu-latest
  
    steps:
    - run: echo "${{ github.event_name }} triggered a linting job on ${{ github.repository }} in branch ${{ github.ref }}"
    - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub."
    - uses: actions/checkout@v1
      with:
          fetch-depth: 0
    - name: Super-Linter
      uses: super-linter/super-linter@v5.7.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DISABLE_ERRORS: false
        VALIDATE_ALL_CODEBASE: true # false once integrated
        VALIDATE_PYTHON_BLACK: true